Implemented fitting of a custom Correlation Function model
danielbattistini/fempy pull request #34
Opened 2024-03-21 23:53 UTC by Marcellocosti

2024-03-26 15:03 UTC, danielbattistini requested changes
Thank you! I think there is some reshaping to be done, you find the details below

2024-03-26 15:03 UTC, danielbattistini commented on fempy/FitCF.py
> +        if('prefitcomp' not in func and func['prefitfile'] is not None):
As we said in person it is probably better to keep the fit to the MC separate

2024-03-29 12:02 UTC, Marcellocosti commented on fempy/CorrelationFitter.hxx
> +              std::string title=";k* (MeV/c);C(k*)") {
Usually we only want to draw all the components with respect to the same component, which describes the minijet background, no?

2024-03-29 12:03 UTC, Marcellocosti commented on fempy/CorrelationFitter.hxx
> +        pad->Update();
I prefer to save in the folder for the fit the spline, so I have the exact shape contributing to the fit

2024-03-29 12:04 UTC, Marcellocosti commented on fempy/CorrelationFitter.hxx
> +        this->fAddModes.push_back(addmode);
I don't understand how can I do this, because we are using lambda expressions so they cannot be updated for every term that is added

2024-03-29 12:06 UTC, Marcellocosti commented on fempy/CorrelationFitter.hxx
> +                            result = pars[nPar]*this->fFitSplines[nSplineComp]->Eval(x[0])*partResult;
I tried thinking about it, but it didn't come to my mind how I could implement this and allow all parameters to be fitted

2024-03-29 12:07 UTC, Marcellocosti commented
Thanks for the suggestions, they indeed make the code clearer. I implemented the majority of the comments leaving just few 
minor ones unresolved.

2024-04-02 15:22 UTC, danielbattistini commented on fempy/CorrelationFitter.hxx
> +              std::string title=";k* (MeV/c);C(k*)") {
Probably, but you can also just draw wrt 1 in the default (as the mj might not be included)

2024-04-02 15:33 UTC, danielbattistini commented on fempy/CorrelationFitter.hxx
> +        this->fAddModes.push_back(addmode);
I have in mind some sort of iterative process where the fit function is built step by step in the Add function and is updated every time a new contribution is added. Let's discuss offline

2024-04-02 15:40 UTC, danielbattistini commented on fempy/CorrelationFitter.hxx
> +                            result = pars[nPar]*this->fFitSplines[nSplineComp]->Eval(x[0])*partResult;
Let's discuss this offline

2024-08-26 17:47 UTC, closed without merging